import os
from datetime import datetime
from pymongo import MongoClient, ASCENDING, DESCENDING
from bson.objectid import ObjectId
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")

client = MongoClient(MONGO_URI)
db = client["AuditHawk"]

audit_reports_col = db["audit_reports"]
transactions_col = db["transactions"]
transaction_batch_col = db["transaction_batch"]
flagged_transactions_col = db["flagged_transactions"]
users_col = db["users"]
trusted_vendors_col = db["trusted_vendors"]


def ensure_indexes() -> None:
    """Create indexes for query/update paths used by GraphQL + ML pipeline."""
    audit_reports_col.create_index(
        [("user_id", ASCENDING), ("uploaded_at", DESCENDING)],
        name="idx_reports_user_uploaded_at",
    )

    transactions_col.create_index(
        [("report_id", ASCENDING), ("user_id", ASCENDING)],
        name="idx_txn_report_user",
    )
    transactions_col.create_index(
        [("report_id", ASCENDING), ("transaction_id", ASCENDING), ("user_id", ASCENDING)],
        name="idx_txn_report_transaction_user",
    )
    transactions_col.create_index(
        [("user_id", ASCENDING), ("flagged", ASCENDING)],
        name="idx_txn_user_flagged",
    )

    transaction_batch_col.create_index(
        [("report_id", ASCENDING), ("user_id", ASCENDING)],
        unique=True,
        name="idx_batch_report_user_unique",
    )

    flagged_transactions_col.create_index(
        [("report_id", ASCENDING), ("user_id", ASCENDING)],
        name="idx_flagged_report_user",
    )
    flagged_transactions_col.create_index(
        [("report_id", ASCENDING), ("transaction_id", ASCENDING), ("user_id", ASCENDING)],
        unique=True,
        name="idx_flagged_report_transaction_user_unique",
    )

    trusted_vendors_col.create_index(
        [("user_id", ASCENDING), ("name", ASCENDING)],
        unique=True,
        name="idx_trusted_vendor_user_name_unique",
    )


# ── Trusted-vendor helpers (HITL Active Learning / Masking) ──

def get_trusted_vendors(user_id: str) -> list[str]:
    """Return trusted vendor names for a specific user."""
    docs = trusted_vendors_col.find({"user_id": user_id}, {"name": 1, "_id": 0})
    return [d["name"] for d in docs if "name" in d]


def add_trusted_vendor(user_id: str, name: str) -> bool:
    """Add a vendor to the trusted whitelist for a specific user (idempotent)."""
    name = name.strip()
    if not name:
        return False
    trusted_vendors_col.update_one(
        {"user_id": user_id, "name": name},
        {"$set": {"user_id": user_id, "name": name}},
        upsert=True,
    )
    return True


def remove_trusted_vendor(user_id: str, name: str) -> bool:
    """Remove a vendor from the trusted whitelist for a specific user."""
    result = trusted_vendors_col.delete_one({"user_id": user_id, "name": name.strip()})
    return result.deleted_count > 0


# ── ML Pipeline & UI State DB Operations ──────────────────────────────

def save_flagged_transactions(user_id: str, report_id: str, anomalies: list[dict]) -> int:
    """Safely bulk-insert anomalies generated by the ML ensemble."""
    if not anomalies:
        return 0
        
    for anomaly in anomalies:
        anomaly["user_id"] = user_id
        anomaly["report_id"] = report_id 
        anomaly["decision"] = "review_required" # Default state for the UI inbox

    try:
        result = flagged_transactions_col.insert_many(anomalies, ordered=False)
        return len(result.inserted_ids)
    except Exception as e:
        print(f"🚨 DB Bulk Insert Warning: {e}")
        return 0

def update_report_status(user_id: str, report_id: str, status: str) -> bool:
    """Update report status to tell the React frontend when math is done."""
    try:
        result = audit_reports_col.update_one(
            {"_id": ObjectId(report_id), "user_id": user_id},
            {"$set": {"status": status}}
        )
        return result.modified_count > 0
    except Exception as e:
        print(f"🚨 Failed to update report status: {e}")
        return False

def update_anomaly_status(user_id: str, report_id: str, transaction_id: str, decision: str) -> bool:
    """
    Triggered by Accept/Reject buttons on the frontend.
    Updates the transaction state (e.g., 'false_positive' or 'confirmed_fraud').
    """
    try:
        result = flagged_transactions_col.update_one(
            {
                "user_id": user_id,
                "report_id": report_id,
                "transaction_id": transaction_id
            },
            {
                "$set": {
                    "decision": decision,
                    "reviewed_at": datetime.utcnow()
                }
            }
        )
        return result.modified_count > 0
    except Exception as e:
        print(f"🚨 Failed to update anomaly status: {e}")
        return False

ensure_indexes()